<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Azure.AI.Projects" Version="2.0.0-beta.2" />
    <PackageVersion Include="Azure.Identity" Version="1.19.0" />
    <PackageVersion Include="Microsoft.Agents.AI.AzureAI" Version="1.0.0-rc5" />
    <PackageVersion Include="Microsoft.Agents.AI.DevUI" Version="1.19.0-preview.260822.1" />
    <PackageVersion Include="Microsoft.Agents.AI.OpenAI" Version="1.19.0" />
    <PackageVersion Include="Microsoft.Agents.AI.Workflows" Version="1.19.0" />
    <PackageVersion Include="OllamaSharp" Version="5.4.10" />
    <PackageVersion Include="OpenTelemetry" Version="1.18.0" />
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.18.0" />
    <PackageVersion Include="StackExchange.Redis" Version="2.9.32" />
  </ItemGroup>
</Project>